### ISSUE TITLE
[Idea] Possibility for using other than local disk

### ISSUE THREAD

**Issue by lsv** [spatie/laravel-backup-server#3]
Would be great to have possibility for fx. S3 storage

**Comment by freekmurze** [comment]
It's kinda difficult to implement because this package assumes that all backupped files are local.

Feel free to work on this yourself, and if you have something workable, let me know!

**Comment by tobyhage** [comment]
Maybe you can use https://opendedup.org/odd/linux-quickstart-guide/ to mount s3 storage as local volume.
